### ISSUE TITLE
Better text editing support (paredit)

### ISSUE THREAD

**Issue by silasdavis** [JonyEpsilon/gorilla-repl#103]
This is great, well done.

I really miss basic editing support working in Gorilla. Paredit support like Session: https://github.com/kovasb/session would be great.

Having a quick single key-combo reload-from-file function (m-g m-r is free) would be useful to allow you to work on the file from another editor/IDE easily. Typing the whole path of the worksheet is too onerous when repeatedly loading the same file.

**Comment by JonyEpsilon** [comment]
This looks useful: http://robert.kra.hn/projects/paredit-js

**Comment by JonyEpsilon** [comment]
Edit name to be a bit clearer about the content.

**Comment by behrica** [comment]
Just a comment here on general better text editing support.

As my (first) Gorilla worksheet was growing bigger, I came as well to the turning point, in which I started to move Clojure code(functions) out of the worksheet into a clojure library (which I do not edit with Gorilla, but with emacs)

I am not 100%, if this is the way to go in every case, but this would some how mean that the code in the worksheet itself stays "very simple"  (some def's + function calls with fixed value parameters)

This means that more advanced text editing functionality is not really needed.

**Comment by behrica** [comment]
@silasdavis 

Maybe it should even do reaload + re-evaluated all cells in a single keypress.

**Comment by behrica** [comment]
What I always do, is to "clean all code-cells" before I save.
(for version controls reasons)
So for me  a single "clean-and-save" key stroke would be nice.
