### ISSUE TITLE
worksheets saved without .clj won't load back in

### ISSUE THREAD

**Issue by lspector** [JonyEpsilon/gorilla-repl#147]
I  do this:
- create a worksheet and evaluate a couple of expressions
- do ctrl+g ctrl+s to save it
- see the file in the top level of the project directory, and a message in the console
- add some new expressions to the worksheet but don't save them
- do ctrl+g ctrl+l to try to load the saved worksheet, providing the same name in the name field

This seems to work (it reverts to the saved state) if the name ends in .clj, but to fail silently otherwise (no message in the console.

**Comment by bherrmann7** [comment]
I tried out gorllia today.  I think it is pretty awesome, however when I went to save my worksheet, I chose the name "Bobs-Nice-Tinkering" and then I wasnt able to load the worksheek back.   Even though I typed the name correctly.    So then I created and saved worksheets "x", "b", "c"...  also couldnt load them no matter what (and never showed up in the load list.)   

I finally downloaded the source and built locally.    Only then when the open workspace dialog showed a "test.clj" file - did it dawn on me that perhaps the worksheets need to be saved with .clj  

I thought gorrllia was pretty broken until I realized this.     

I think either it should allow worksheets to be saved/loaded with any name.     Or it should strongly encourage saving with the proper extension.  

Of course, I should submit a patch...

**Comment by dasmoth** [comment]
I've just run into this issue as well (think I've missed it in the past because I've tended to just manuall create ?filename=foo URLs).  Like @bherrmann7 I think that encouraging the use of a suitable extension in the Save box would be a big help.

**Comment by JonyEpsilon** [comment]
Yeah, this is a bit of a mess at the moment. I think the best thing right now would probably be to remove the restriction on the filename when loading. I'm currently pondering changing the UI for load/save a bit, so I don't think we should do too much just now.

**Comment by benfb** [comment]
This should be fixed in the next release, at least to some extent. `.clj` is prepopulated in the save dialog.
