### ISSUE TITLE
Viewer docs for viewing Gists are incomplete.

### ISSUE THREAD

**Issue by dasmoth** [JonyEpsilon/gorilla-repl#173]
The Gist URL template [here](http://gorilla-repl.org/viewer.html) seems to be incomplete -- I can't get this to work without adding an extra filename= parameter

Compare:

          http://viewer.gorilla-repl.org/view.html?source=gist&id=3bdede1df8232d255e35&filename=biodatoms-demo

with:

         http://viewer.gorilla-repl.org/view.html?source=gist&id=3bdede1df8232d255e35

In the latter case, there's also an error in the JS console:

       Uncaught TypeError: Cannot read property 'content' of undefined

I'm also wondering if it might be worth defaulting the filename for gists containing only one file.

**Comment by JonyEpsilon** [comment]
Have updated the docs, and made single-file gists default to the only file, as suggested. Thanks for the report :-)

BTW, that worksheet you posted a link to looks neat :-)
