### ISSUE TITLE
Support for secure Websocket connection

### ISSUE THREAD

**Issue by behrica** [JonyEpsilon/gorilla-repl#177]
A lot of coorporate firewalls block WebSocket connections (ws://), but do work with secure websocket.

It would be usefull if gorilla could work with a wss connection.

**Comment by JonyEpsilon** [comment]
This is tricky to support easily/directly as the http server, http-kit, that Gorilla uses doesn't support secure connections itself.

I often tunnel Gorilla over ssh, as our work firewall blocks everything except ssh. That works very well, if you have the ability to make an ssh connection to the server.

An other option, if you have the ability on the server, is to proxy Gorilla server-side with nginx. There are some notes on that on the http-kit website:

http://www.http-kit.org/migration.html

The final option would be to port Gorilla over to a different web-server that does support https/wss. I haven't looked in to that, but it would be a possibility.

**Comment by behrica** [comment]
I know how to tunnel something over ssh, but is there something special to do for the websocket connection ?

Or is it enough to make a normal ssh tunnel to "my.server:8999" (where 8999 is the port of the gorilla web app) and then it will just work ?

**Comment by dasmoth** [comment]
Switching to using Jetty 9 (good support for HTTPS and Websockets) would be reasonably straightforward.  The basic changes to support this are [here](https://github.com/dasmoth/gorilla-repl/tree/ring-jetty9).  But still need to add an extra option for passing in a key-store when serving over HTTPS.

I think it's an open question whether moving to Jetty would be a good idea.  It's a lot heavier-weight than httpkit.  On the other hand, it's got a lot more features and seems to be ubiquitous in the Clojure world.  I thought it was worth a bit of investigation, anyway.

**Comment by JonyEpsilon** [comment]
@behrica Yes, the websocket connection is on the same port as the HTTP connection, so tunnelling that port should be sufficient.

@dasmoth Neat! Gorilla used to run off Jetty, but I switched to http-kit when I started using websockets. Somehow I didn't see that Jetty 9 ring adapter. I'm happy with switching back if it's helpful.

I just tried a quick comparison of the size of an uberjar (to get an idea of the total size of the dependencies) for both the http-kit branch and your jetty9 branch. They're with about 1.5k of each other, which surprised me. Start up time doesn't seem significantly different (eyeballing it, not measuring).

**Comment by behrica** [comment]
I tried the ssh tunnel and it works as expected.

So for me, the issue is resolved.

I made a PR for adding a hint to the ssh tunnel to the docu.

**Comment by JonyEpsilon** [comment]
Thanks for the docs PR @behrica - I'll get in merged in as soon as I have a chance.

I think, in terms of this issue, let's close it, to be re-opened if there's wider demand for the feature. @dasmoth 's solution looks like a good one if we decide to go that way.

**Comment by zcaudate** [comment]
I would like for @behrica's PR to be merged it solves a couple of problems such as when the only available option to get a repl into a deployed application is through a https/wss connection.
