### ISSUE TITLE
A Dream: Change classpath of gorilla without full restart ?

### ISSUE THREAD

**Issue by behrica** [JonyEpsilon/gorilla-repl#178]
@JonyEpsilon 

I know, this is between hard and impossible to achieve with Clojure/Java.
But I just want to here your opinion.

The usecase is clear: I want Gorilla on a remote server and I want to add libraries to my repl without need of ssh to the server and edit the project.clj and restart gorilla repl....

I know there are things like alembic, but they do not work always.

I can do this with Rstudio server for R. I just have a web interface into RStudio and never need to leave it... For me a killer feature of R(Studio).

I believe this can only be done, if the main web app you connect to, is either not jvm based, but something else, or a first jvm which somehow starts a second jvm..

I am still dreaming about a web based REPL (or Clojure IDE), which allows this....

Just le me know your opinion on this.

**Comment by behrica** [comment]
Maybe we can close this.

I found a workarround, which is "good enough" for me.
I installed shellinabox on my server.

I use it to only to start gorilla and change the project.clj if needed.
This is fine for me.

**Comment by dasmoth** [comment]
Have you looked at [Alembic](https://github.com/pallet/alembic)?

I can't see any reason why it shouldn't coexist peacefully with Gorilla, and a quick test worked fine.

**Comment by JonyEpsilon** [comment]
Alembic is useful a lot of the time, but there are some things that require a restart, particularly if you're doing a lot of java intro. So, yes, I think it would be very useful to have Gorilla be able to restart the nREPL server. There's an existing issue, #125 , which I think pretty much covers this, so I'm going to close this one.
