### ISSUE TITLE
Worksheet fails saving on big plots.

### ISSUE THREAD

**Issue by whilo** [JonyEpsilon/gorilla-repl#186]
When I tried to save a sheet with a fairly large plot (8 MiB the svg alone), it just told me `Failed to save 'sheet-name.clj'`. When I (finally) looked in the browser console it was more informative:

~~~
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
~~~

I guess it is before entering the save handler in `gorilla-repl.core` already happening in http-kit, but I am not sure. Either the error should be more informative by being shown in the failed message or probably it should still work with large attachments (the size already hurts scrolling and browser performance, but this is more intuitive imo.)

**Comment by JonyEpsilon** [comment]
Oh dear, that's not a good thing at all! I'm guessing there's some config in http-kit - I'll take a look.

**Comment by ghubber** [comment]
The parameter is `:max-body` and it defaults to 8 MiB.

http://www.http-kit.org/server.html
