### ISSUE TITLE
Add command to execute blocks "after current block"

### ISSUE THREAD

**Issue by behrica** [JonyEpsilon/gorilla-repl#189]
As my analysis gets bigger, I start changing code in certain blocks, which makes all "later" blocks invalid.

So I see myself a lot of times wanting to execute all blocks "below" a current block.
(As I cannot, I do by hand or execute all blocks which takes more time then needed.)

A specific command for this would be very helpful

**Comment by JonyEpsilon** [comment]
Yes, I agree that this would be a good thing.

**Comment by benfb** [comment]
Should be fixed in the next version. `ctrl-g ctrl-enter` on Mac, `alt-g alt-enter` elsewhere.
