### ISSUE TITLE
support ParEdit like mode

### ISSUE THREAD

**Issue by behrica** [JonyEpsilon/gorilla-repl#191]
It could me nice to use ParEdit like functionality in Gorilla.

There is a plugin for CodeMirror for this.

**Comment by JonyEpsilon** [comment]
I agree that it would be good to support this. There's already an issue which is essentially this (although has a slightly cryptic name) #103, so I'm going to close this one. If there's a working CodeMirror plugin then it should be quite easy. I'll take a look when I have some free time, which at the rate things are going at the moment will be around 2020!

**Comment by JonyEpsilon** [comment]
Going to close as duplicate.
