### ISSUE TITLE
Load as a link

### ISSUE THREAD

**Issue by puredanger** [JonyEpsilon/gorilla-repl#194]
It would be useful to create webs of linked clj files so that a tutorial could be broken up into pieces (for example). 

One way to do this would be to be able to use markdown that created a link that would cause a load of a different file to occur.

**Comment by kpfell** [comment]
Apparently, this is already possible! Try
```
[Some link](/worksheet.html?filename=src/some_directory/some_other_file.clj)
```
in Markdown.

The one catch is that, if the Markdown section is set to be editable, you'll have to right click, then select "Open Link in New Tab," as the worksheet will otherwise register the click as you wanting to edit the Markdown, rather than you wanting to follow the link.

**Comment by JonyEpsilon** [comment]
Yes, the infrastructure for this is already present. If we were to implement the suggestion of read-only markdown segments in #193 then this would work quite nicely, I'd imagine.

**Comment by JonyEpsilon** [comment]
p.s. One possible snag is that, because Gorilla runs in the context of a particular project, it's only really possible to link worksheets like this if they are in the same project. In practice, this probably isn't much of a limitation though.

**Comment by puredanger** [comment]
Same project seems totally fine to me and I'm finding this workable as is right now (and would be extra great with read-only segments). Feel free to close!

**Comment by JonyEpsilon** [comment]
OK, will close this on the understanding that it will get better once read-only segments are working :-)
