### ISSUE TITLE
Extending the viewer to work with Bitbucket repos

### ISSUE THREAD

**Issue by shark8me** [JonyEpsilon/gorilla-repl#197]
Hi all,

I'd like to extend the online viewer to work with repositories other than Github, such as BitBucket. I can't seem to find the code for the viewer on the repo. 
Please point out the repo where the viewer is hosted, and if it can be modified for this purpose.

**Comment by JonyEpsilon** [comment]
Hi. Yes, this would be a great feature :-) The viewer code is in with the main gorilla-repl client code. The relevant files are:

https://github.com/JonyEpsilon/gorilla-repl/blob/develop/resources/public/js-viewer/main-viewer.js
https://github.com/JonyEpsilon/gorilla-repl/blob/develop/resources/public/js-viewer/github.js

Jony

**Comment by shark8me** [comment]
Thanks!
How do I test this? Is there a set of instructions to run the viewer?

**Comment by JonyEpsilon** [comment]
The easiest way to test is to use the Gorilla REPl server to serve the page. If you issue `lein run` from within the gorilla-repl project directory, then you can navigate to:

http://127.0.0.1:port/view.html?querystring

where you'll need to get the right port (printed by the Gorilla server on startup) and the query string that your bitbucket code requires.

**Comment by JonyEpsilon** [comment]
Gonna re-open this as the new behaviour isn't documented on the website.

**Comment by JonyEpsilon** [comment]
Finally documented this!
