### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by mikepence** [JonyEpsilon/gorilla-repl#202]
There are lots of interesting ways that I would like to extend Gorilla. A mailing list would be most welcome.

**Comment by JonyEpsilon** [comment]
Hi Mike,

 I've got mixed feelings about this one. I can see the points in favour, but there's also something useful about keeping all of the discussion in one place (issues) and quite focussed. I suppose one option would be to try it ...


Jony

**Comment by benfb** [comment]
Seems like Github Issues has become the de-facto center of discussion anyway.
