### ISSUE TITLE
cancelling current command / resetting server

### ISSUE THREAD

**Issue by fwood** [JonyEpsilon/gorilla-repl#205]
It would be awesome if I could interrupt the current command processing and/or do a hard reset of the server without having to SIGINT it form the command line.

**Comment by JonyEpsilon** [comment]
Yes, this is very high on my list of things that I want to fix.

I've tried a number of times to implement the interrupt command and failed! There's an existing issue for it, with some discussion #18.

Resetting the server would also be useful. I've been holding off on looking at that until the dust settles on the wider issue of how Gorilla manages multiple projects and REPL processes (see #184 for some discussion). I think, though I'm heading towards keeping one Gorilla process per project, for simplicity. If that is the way we go, then resetting the server will be relatively simple to implement. The only new thing that is needed is a way for the client to reconnect to the server, which might be a useful feature in its own right. There's an issue with some discussion about this #125.

I'm going to close this issue, as I think it's pretty much covered by the other two.
