### ISSUE TITLE
Can't exit command menu via keyboard

### ISSUE THREAD

**Issue by spieden** [JonyEpsilon/gorilla-repl#212]
With the command menu open (ctrl+g ctrl+g), there doesn't seem to be a way to exit it via the keyboard. i.e. You can click outside of it to exit, but I'd expect "esc" or another "ctrl+g ctrl+g" to close it as well.

**Comment by JonyEpsilon** [comment]
Esc should close the menu (and does on my machine). Could you share your OS and browser version so we can try and track down the problem?

**Comment by spieden** [comment]
Ah, I bet it's Vimium that's trapping the escape key. That always gets me https://github.com/philc/vimium/issues/239

What do you think about a second cntrl+g cntrl+g closing the menu if it's already open?

**Comment by JonyEpsilon** [comment]
Yes, that sounds like a natural way to do it.

**Comment by benfb** [comment]
Looks like this was fixed in vimium a while ago.
