### ISSUE TITLE
Evaluate current segment and retain focus

### ISSUE THREAD

**Issue by spieden** [JonyEpsilon/gorilla-repl#213]
Often I'm working in a segment and want to evaluate what I have so far. This without having to reacquire focus to continue working on the segment. Maybe we could make "cntrl+shift+enter" do this?

**Comment by JonyEpsilon** [comment]
Great idea! That would be a good feature I think.

**Comment by benfb** [comment]
This should be fixed in the latest version here: https://github.com/JonyEpsilon/gorilla-repl/commit/24e0d4075b66cc451f7c9f968f0c1dda9f4e34f6

`ctrl-enter` on Mac, `alt-enter` elsewhere
