### ISSUE TITLE
Eagerly evaluate require/use for immediate completion

### ISSUE THREAD

**Issue by spieden** [JonyEpsilon/gorilla-repl#214]
Often I add a require form to a segment and wish to complete symbols from its namespace in the very next form. Currently I have to evaluate the segment and refocus it to do so. Would there be any downsides to evaluating new requires when the completion is activated?

**Comment by JonyEpsilon** [comment]
One of my principles with Gorilla has been to keep it as simple and unsurprising as possible. I think that this behaviour, although it could save some typing, might be a bit surprising to users, so I'd not favour adding it.
