### ISSUE TITLE
Enlive tutorial refers to html-indent, but location unknown 

### ISSUE THREAD

**Issue by GHExplorer** [JonyEpsilon/gorilla-repl#218]
Hi,

I know this is unrelated to the gorilla-repl per se, but at

http://viewer.gorilla-repl.org/view.html?source=github&user=shark8me&repo=clojure-examples&path=src/enliven.cljw

there is an Enlive tutorial, which refers to html-indent:

(ns enliven
  (:require [net.cgrand.enlive-html :as html]
            [hiccup.core :as hc]
            [html-indent :refer [view]]               <======= HERE
            [clojure.java.io :as io]))
(view (hc/html [:div]))

There's no projects.clj example there, don't know who the author is, and cannot locate a Clojure html-indent library on the web.

Does anyone know where this library is located?

**Comment by JonyEpsilon** [comment]
Is it this?

https://github.com/shark8me/clojure-examples/blob/master/src/html-indent.cljw

**Comment by GHExplorer** [comment]
That's the one, thanks JonyEpsilon.
