### ISSUE TITLE
3D Plotting

### ISSUE THREAD

**Issue by squest** [JonyEpsilon/gorilla-repl#223]
Hi,

First of all thanks for this plugin, it helps me a lot in making my daily data analysis tasks much more enjoyable. However, I need to plot some 3d charts/points. From my understanding, it can't do such thing for now, however can someone point me which part of it I can play with so that I can do those 3d stuffs?

Thanks

**Comment by JonyEpsilon** [comment]
Anything that the web browser can display can be included in Gorilla REPL, so the first step would probably be trying to identify a javascript library that can do what you want to do. Once you got that, then you can build a renderer plugin to make it easy to use. You could look at https://github.com/wiseman/leaflet-gorilla as an example of how to use an external js library to render content in Gorilla.

**Comment by aadrian** [comment]
Plotly seems to have a few 3d chart representations (3d line and 3d surface seem useful):
https://plot.ly/javascript/#3d-charts

But to be able to render all sort of 3D stuff, a more low level lib like http://threejs.org/ would be required.

**Comment by findmyway** [comment]
Recently I wrote a simple wrapper for plotly integrated with gorilla-repl. May it will help someone else looking for 3d charts in gorilla.

https://github.com/findmyway/plotly-clj

**Comment by benfb** [comment]
That wrapper is great! I'm going to close this issue, but thanks for your work!

**Comment by JonyEpsilon** [comment]
That's really nice! :-)
