### ISSUE TITLE
Lookup in Clojuredocs no longer seems to work

### ISSUE THREAD

**Issue by JonyEpsilon** [JonyEpsilon/gorilla-repl#224]
At least, on a Mac in Safari 8.0.8 it isn't working. Just sends to an "about:blank" page.

**Comment by M40** [comment]
same on windows 7 machine, but on linux mint and firefox it's working normally, from both "lein run" and from running a standalone jar

**Comment by JonyEpsilon** [comment]
Thanks for that, I'm sure it will be helpful :-)

**Comment by peterfoldi** [comment]
@msamir I can't confirm this: here it's broken on both osx and linux. And my fix fixed it on both.
