### ISSUE TITLE
Font rendering

### ISSUE THREAD

**Issue by uroybd** [JonyEpsilon/gorilla-repl#225]
I have some Bengali text in my worksheet and it is not showing properly in the online viewer. Here it is: http://viewer.gorilla-repl.org/view.html?source=github&user=uroybd&repo=uroybd.github.io&path=ws/sierpinski.clj

**Comment by JonyEpsilon** [comment]
Thanks for the report and the test case. Looks like this is a problem with how I'm decoding the base64 encoded reply from Github. Think I have a fix, will deploy it later once I have a more reliable internet connection :-)

**Comment by JonyEpsilon** [comment]
OK, deployed, and looks to be working to me.
