### ISSUE TITLE
Autocomplete list show all values as undefined

### ISSUE THREAD

**Issue by tcalsaverini** [JonyEpsilon/gorilla-repl#238]
![screen shot 2015-12-04 at 20 53 04](https://cloud.githubusercontent.com/assets/13474052/11603478/1dd349de-9ac9-11e5-8eec-aec48a736bee.png)

**Comment by tcalsaverini** [comment]
Autocomplete is now working for me as of version 0.3.5

**Comment by JonyEpsilon** [comment]
Thanks for following up, will close this issue.
