### ISSUE TITLE
Exception information filters .cljc files

### ISSUE THREAD

**Issue by davesann** [JonyEpsilon/gorilla-repl#239]
If you have an exception throw in a .cljc file, all you will see for lines information in that file is a red list point. It appears that the information is filtered out.

renaming to .clj is a short term fix if anyone else encounters this problem.

**Comment by benfb** [comment]
@davesann I believe this is due to `include-file?` previously only checking for limited extensions. Does this still occur with the latest version of gorilla (0.4.0)?
