### ISSUE TITLE
breaks refactor-nrepl

### ISSUE THREAD

**Issue by huahaiy** [JonyEpsilon/gorilla-repl#242]
For a project, emacs jack-in repl will be fine, but connecting to a gorilla-repl will break refactor-nrepl, getting the following:

; CIDER 0.11.0snapshot (package: 20151224.1145) (Java 1.8.0_66, Clojure 1.7.0, nREPL 0.2.12)
WARNING: The following nREPL ops are not supported:
artifact-list artifact-versions clean-ns extract-definition find-symbol find-used-locals hotload-dependency namespace-aliases rename-file-or-dir resolve-missing stubs-for-interface version warm-ast-cache
Please, install (or update) refactor-nrepl and restart the REPL.
You can mute this warning by changing cljr-suppress-middleware-warnings.
WARNING: clj-refactor and refactor-nrepl are out of sync.
Their versions are 2.0.0-SNAPSHOT (package: 20151210.200) and n/a, respectively.
You can mute this warning by changing cljr-suppress-middleware-warnings.

**Comment by JonyEpsilon** [comment]
Sorry for the slow reply.

This is something of an endless problem, I'm afraid. I think it boils down to an issue that nREPL doesn't gracefully handle more than one tool trying to determine the middleware stack. I try and keep Gorilla up to date with the latest CIDER middleware, but beyond that I'm not sure it's easy to do very much.

**Comment by benfb** [comment]
I'll be trying to keep Gorilla's CIDER middleware more up to date.
