### ISSUE TITLE
CTRL+space autocomplete for `$function` names

### ISSUE THREAD

**Issue by drewnoff** [JonyEpsilon/gorilla-repl#243]
autocomplete with CTRL+space doesn't work for functions with names starting with `$` sign

[lein-gorilla "0.3.5"]

**Comment by JonyEpsilon** [comment]
I can't reproduce this ... it seems to work for me on Mac OS 10.11.3, Safari 9.0.3. Could you share your configuration so that we can try and figure out where the problem lies?

**Comment by benfb** [comment]
If this problem is still occurring, feel free to leave a comment here. Otherwise, it seems to be resolved.
