### ISSUE TITLE
Add an Undo command

### ISSUE THREAD

**Issue by mikeivanov** [JonyEpsilon/gorilla-repl#247]
Deleting segments is destructive, I've lost a good chunk of unsaved code by accidentally deleting a segment. Some sort of Undo command is necessary.

**Comment by JonyEpsilon** [comment]
:-)

I've found that doing it once or twice is sufficiently painful to condition one out of doing it ever again. But I would concede that that is not the gold standard for user experience :-) Thanks for the PR, will get it merged in.
