### ISSUE TITLE
latex-view generated Tex overruns segment.

### ISSUE THREAD

**Issue by alexgian** [JonyEpsilon/gorilla-repl#250]
Not sure what one could do about this, but if a line of generated TeX code is longer than the segment width, it is simply allowed to overrun for as long as it wants, which is unsightly.
Allowing the segment div to auto-adjust is probably overkill.  
Perhaps allowing adjustment of TeX font size as an option might help in marginal cases.
Or perhaps allowing the segment to become scrollable.

No real suggestions here, just reporting the fact.

**Comment by JonyEpsilon** [comment]
Yeah, I'm not sure I can think of a good solution for this one.

You can rescale the TeX output by right-clicking on it, but this is a pain, and also not persistent.

**Comment by alexgian** [comment]
OK, I'll try the right-clicking workaround.
I am actually closing this for the moment, even if unsolved, as I don't think it's very high up on the priority list.  I just wanted to highlight it, so to speak.

**Comment by alexgian** [comment]
Given that the resized area is rendered *within* a scrolled window (when right-clicking), might this not offer some kind of solution - by rendering the TeX inline **with** the scrolling window instead of just "bare"?
