### ISSUE TITLE
Eval cell without jumping to the next one

### ISSUE THREAD

**Issue by rqcy** [JonyEpsilon/gorilla-repl#258]
Hi, I was not able to find a way to evaluate a cell without changing the pointer's position and jumping to the next cell.

A useful (and consistent with IPython Notebook) shortcut would be Ctrl-Enter.

Thanks!

**Comment by benfb** [comment]
This should be fixed in the next version. `Ctrl-Enter` on Mac or `Alt-Enter` elsewhere.
