### ISSUE TITLE
Add a command mode and edit mode

### ISSUE THREAD

**Issue by drewokane** [JonyEpsilon/gorilla-repl#261]
In using the gorilla notebook I have run into the already mentioned frustration of `emacsy` keybindings not working (on Mac at least). I thought a bit about this and experimented and had an interesting idea I thought I would suggest. Why not have a command mode, where the gorilla keybindings work for editing cells, moving things, saving the notebook, etc, and then an edit mode where "regular" keyboard bindings work, e.g. `emacs` keybindings for text editing. A preliminary search within `Mousetrap` suggests to me (at least from my limited experience) that we could pause and un-pause the gorilla keybindings. I'm willing to put in the time for this, with the caveat that I haven't worked in `javascript` before.

**Comment by benfb** [comment]
Feel free to open a PR for this if you get the time—otherwise it's probably not worth risking the simplicity of gorilla for beginners.

**Comment by drewokane** [comment]
PR has been added: #262

**Comment by benfb** [comment]
Ah, great thanks! That will actually help with #185 too.
