### ISSUE TITLE
Support doc / source

### ISSUE THREAD

**Issue by betabrain** [JonyEpsilon/gorilla-repl#264]
I find `(doc ...)` and `(source ...)` very convenient for quickly looking stuff up. Unfortunately they don't work in Gorilla.

**Comment by betabrain** [comment]
Is there a way to automatically extend the default workbook as follows on startup:
```Clojure
(ns khaki-grove
  (:require [gorilla-plot.core :as plot])
  (:use [clojure.repl :only [doc source]]))
```

**Comment by benfb** [comment]
I would generally like to avoid adding more imports to everyone's code automatically. If you find a way to make this an option/config flag, let me know--it does seem useful.
