### ISSUE TITLE
Error running list-plot

### ISSUE THREAD

**Issue by jsgrahamus** [JonyEpsilon/gorilla-repl#265]
On Ubuntu 16.10 (?) x64, following tutorial, got an error when trying to run it:

(list-plot (1 2 3 4 5))

---

Exception thrown: java.lang.ClassCastException (java.lang.Long cannot be cast to clojure.lang.IFn)
eval9950 - calm-dawn - (form-init8927565946900784424.clj:1)
eval9950 - calm-dawn - (form-init8927565946900784424.clj:1)
eval - (Compiler.java:6927)
eval - (Compiler.java:6890)
eval - clojure.core - (core.clj:3105)
eval - clojure.core - (core.clj:3101)

---

steve@steve-Satellite-L555D:~/foo$ ls
CHANGELOG.md  doc  LICENSE  project.clj  README.md  src  target  test
steve@steve-Satellite-L555D:~/foo$ cat project.clj 
(defproject foo "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :plugins [[org.clojars.benfb/lein-gorilla "0.4.0"]]
  :main ^:skip-aot foo.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
steve@steve-Satellite-L555D:~/foo$

**Comment by JonyEpsilon** [comment]
It looks like you're accidentally calling 1 as a function. Either of:

(list-plot [1 2 3 4 5])

(list-plot '(1 2 3 4 5))

should work. When you get an "xxx cannot be cast to clojure.lang.IFn" error in clojure it's almost always a sign that you've accidentally got something inappropriate at the front of a function call form.
