### ISSUE TITLE
cdn.mathjax.org has been retired

### ISSUE THREAD

**Issue by ribelo** [JonyEpsilon/gorilla-repl#269]
MathJax CDN shutting down on April 30, 2017.

https://www.mathjax.org/cdn-shutting-down/

**Comment by jsa-aerial** [comment]
I see someone has beat me to this. It looks like the suggested change is to change

https://cdn.mathjax.org/mathjax/2.7-latest/MathJax.js  references to

https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js

This will need to change in the various *.html templates in Gorilla

**Comment by jsa-aerial** [comment]
OK, I can confirm that swapping those as described in worksheet.html and view.html works

**Comment by benfb** [comment]
This will go out in the next release. Thanks for bringing this to my attention!
