### ISSUE TITLE
How do I use gorilla outside leiningen?

### ISSUE THREAD

**Issue by stuarthalloway** [JonyEpsilon/gorilla-repl#272]
Leiningen is a build tool, and gorilla is an app, or better yet, a library. How do I use it outside of leiningen?

**Comment by benfb** [comment]
I don't think this is currently possible. There's a ticket for implementing boot support (#259), but it would be pretty difficult to extract gorilla from leiningen. You can take a look at the lein plugin [here](https://github.com/JonyEpsilon/lein-gorilla/tree/develop) for an idea of how it's implemented, though.
