### ISSUE TITLE
(Request/Question) gorilla-repl... script?

### ISSUE THREAD

**Issue by michaellindon** [JonyEpsilon/gorilla-repl#277]
I am using gorilla-repl interactively to make a variety of plots to visualize results from a very large computation. At the moment I just re-run the cells in the worksheet by hand once computations have finished. Once these are done, I save the webpage and convert to a pdf.

The challenge I have is that I need to do this for 300 datasets. Naturally I do not want to re-run the cells by hand for all 300. Is there a way in which gorilla-repl can be accessed programmatically? Ideally I would like for a given input dataset, computation to be run, all figures be re-plotted in all the relevant cells and then the webpage is saved.

Currently I do not know how to do this. I can plot using an alternative library, Jfreechart in incanter for instance, which allows me to save figures to a png, but I prefer the plotting functionality in gorilla-repl. Is there a way to automatically generate the worksheet after computation and save?

**Comment by benfb** [comment]
#259 might give you some help?

**Comment by ghost** [comment]
Yeah, you can add deps in the boot script which will be available to your app.

**Comment by benfb** [comment]
I'm closing this for now. Let me know if you need clearer instructions.
