### ISSUE TITLE
Update to support Java 9

### ISSUE THREAD

**Issue by johannesborgstrom** [JonyEpsilon/gorilla-repl#282]
When attempting to run under Java 9, an exception is thrown due to a library no longer loading automatically:
`$ lein gorilla`
`clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/server.clj:1:1)`

Can you add this module explicitely, e.g.
`:jvm-opts ["--add-modules" "java.xml.bind”]`
?
[See also](https://github.com/http-kit/http-kit/issues/356)

**Comment by benfb** [comment]
This will be in the next release, thanks for the tip!

**Comment by benfb** [comment]
I just pushed the latest release of gorilla and the Lein plugin to a different repository/fork (`org.clojars.benfb/gorilla-repl`). The code for that plugin is located here: https://github.com/benfb/lein-gorilla. Jony has been mostly inactive, but I didn't want to make code changes without his approval under his name, so I created the other repository. Please raise any issues you have there. Thanks!

The newly-released version (0.5.0) of the forked plugin should fix this. To use it, just change the `lein-gorilla "0.4.0"` plugin to `org.clojars.benfb/lein-gorilla "0.5.0"`.
