### ISSUE TITLE
LaTeX rendering is not working for certain equations

### ISSUE THREAD

**Issue by ghost** [JonyEpsilon/gorilla-repl#284]
```
When @@a \ne 0@@, there are two solutions to @@\(ax^2 + bx + c = 0\)@@ and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$

$$F_{n}=F_{n-1}+F_{n-2}$$
```
The last one does not render. The first sentence works.

---

**Screenshot**
<img width="832" alt="gorilla-repl-latex-issue" src="https://user-images.githubusercontent.com/1277952/39594115-61172d98-4f29-11e8-8bb3-ab4ac81a1d2d.png">

**Comment by gscacco** [comment]
The problem is the underscore symbol. The following works:

$$F\_{n} = F\_{n-1}+F\_{n-2}$$

**Comment by benfb** [comment]
@gscacco Thanks for covering this!
