### ISSUE TITLE
Autosave Option

### ISSUE THREAD

**Issue by semperos** [JonyEpsilon/gorilla-repl#48]
Opening an issue instead of issuing a PR directly because introducing options of any kind begs the question of: what plans do you have for configuration, either via the `lein gorilla` subcommand or via the UI itself during a session?

If you indicate which direction you plan/would like to go, if either, I'll be happy to put together a PR for an option to auto-save worksheets. Nothing like accidentally refreshing your tab...

Thanks for your wonderful work.

**Comment by mikepence** [comment]
+1

**Comment by iantruslove** [comment]
@JonyEpsilon re autosave and (auto-)reload: +1, that would be really great. Personally, I like having emacs and gorilla open side-by-side, and whilst reloading the worksheet in Gorilla is a tiny bit cumbersome, it's nice to be able to hop back and forth. FWIW autosave and autoreload would obviously make my workflow better!

**Comment by dtolpin** [comment]
This simple diff below will autosave the worksheet into a backup (~ appended) at most once per minute if  there might have been a change to the worksheet.  I am hesitant about issuing a PR because this asks for configuration parameters, but since I added this my gorilla-repl experience is significantly less frustrating. 

    diff --git a/resources/public/js/main.js b/resources/public/js/main.js
    index cd96322..f9c8c85 100644
    --- a/resources/public/js/main.js
    +++ b/resources/public/js/main.js
    @@ -33,6 +33,12 @@ var app = function () {
             self.filename(newFilename);
             self.worksheet(newWorksheet);
             newWorksheet.addEventHandlers();
    +
    +		// If the worksheet is named, a backup is saved automatically on autosave triggers.
    +		eventBus.on("worksheet:leaveBack worksheet:leaveForward worksheet:segment-clicked",
    +				function (e) {
    +					eventBus.trigger("app:autosave");
    +				});
         };
     
         // This starts the application. First of all we ask the server for configuration information, and then prepare the
    @@ -135,6 +141,29 @@ var app = function () {
             });
         };
     
    +	// Support for asynchronous autosave
    +	var autosave_interval = 60000;
    +	var async_autosave = undefined;
    +
    +	var do_autosave = function (filename) {
    +		var filename_as = filename + "~";
    +		$.post("/save", {
    +			"worksheet-filename": filename_as,
    +			"worksheet-data": self.worksheet().toClojure()
    +		}).fail(function () {
    +			self.flashStatusMessage(
    +					"Failed to autosave worksheet: " + filename
    +					+ " as: " + filename_as, 2000);
    +		});
    +		clearTimeout(async_autosave);
    +		async_autosave = undefined;
    +	};
    +	var autosave = function(filename) {
    +		if(!async_autosave)
    +			async_autosave = setTimeout(function () {do_autosave(filename);},
    +					                    autosave_interval);
    +	}
    +
         var loadFromFile = function (filename) {
             // ask the backend to load the data from disk
             $.get("/load", {"worksheet-filename": filename})
    @@ -204,6 +233,12 @@ var app = function () {
             } else self.saveDialog.show();
         });
     
    +    eventBus.on("app:autosave", function () {
    +        var fname = self.filename();
    +        if (fname !== "")
    +			autosave(fname);
    +    });
    +
         eventBus.on("app:saveas", function () {
             var fname = self.filename();
             self.saveDialog.show(fname);

**Comment by JonyEpsilon** [comment]
Thanks for this, I would definitely like to incorporate something like this into the next release.

**Comment by alguevara7** [comment]
Just in case this helps someone, I've been quite happy with this poor man's version of autosave :)

`window.setInterval(function() { eventBus.trigger("app:save"); }, 1000 * 60);`

**Comment by e0d** [comment]
@zb0th lovely hack.  Running in incognito window to solve for browser keybinding conflicts resulted in lost work.

**Comment by rrrnld** [comment]
Is there any progress on this? This has bitten me repeatedly, which is a petty because I otherwise really love working with gorilla-repl. I would also be happy with a `You have unsaved changes. Want to save all changed files?` prompt when `Ctrl + C`ing.
