### ISSUE TITLE
Plots with date axes

### ISSUE THREAD

**Issue by JonyEpsilon** [JonyEpsilon/gorilla-repl#89]
Think this is supported by Vega, so shouldn't be difficult. Mentioning @aaelony for continuity.

**Comment by aaelony** [comment]
Thank-you.

**Comment by rqcy** [comment]
Would you consider re-opening this issue?  Even if you don't have time/motivation to implement it, perhaps someone else could submit a PR.  You could tag it as “help-needed” or similar.  Using dates as x-axis is quite basic.

Thanks, I really like Gorilla REPL. :)
